name: Greet first-time contributors

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: > 'Project Hatchet studios would like to thank you
                         for taking time out of your day to test our mod and contribute
                          by making an issue request. Congratulations on filling out your first issue report.
                           I hope you found the simple process and easy to understand. 
                           If not, reach out to us on discord, and we will resolve the issue.'

        pr-message: >'Project Hatchet studios would like to thank you for donating your time
         to work on our open source project; developers like you make this project possible. 
          Congratulations on filling out your first PR request. '
